### ISSUE TITLE
Logout 페이지 레이아웃 생성

### ISSUE THREAD

**Issue by Eugenius1st** [RE-BON/ReBoN#103]
### Description
Logout 페이지 레이아웃 생성
### Todo
- [x] Logout 페이지 레이아웃 생성
- [x] Logout 모달창 생성
- [x] Post 페이지 별 수정
- [x] 이전 페이지들의 모달창 수정

**Comment by Eugenius1st** [comment]
완료
