### ISSUE TITLE
Mypage 페이지 디자인 보완

### ISSUE THREAD

**Issue by Eugenius1st** [RE-BON/ReBoN#107]
### Description
Mypage 페이지 디자인 보완

### Todo
- [x] header 중첩 안되도록 수정
- [x] edit 컴포넌트 닉네임 input 수정
- [x] 수정완료시 버튼 클릭시 닉네임 적용
- [x] 왼쪽 sideBar에도 닉네임 적용
- [x] sideBar 색깔 추가
- [x] edit 컴포넌트 마케팅 수신동의 버튼 조건 추가
- [x] footprint 디자인 보완
- [x] footprint 모달창
- [x] bookmark 디자인 보완
- [x] bookmark 모달창
