### ISSUE TITLE
Header 컴포넌트 디자인 수정

### ISSUE THREAD

**Issue by Eugenius1st** [RE-BON/ReBoN#108]
### Description
Header 컴포넌트 디자인 수정

### Todo
Header
- [x] header 모달창 디자인 수정
- [x] 전역 스타일적용
- [x] postion 중첩 수정

Header
- [x] footprint 모달창 수정
