### ISSUE TITLE
카테고리 별 가게 리스트 가져오는 기능

### ISSUE THREAD

**Issue by KJunseo** [RE-BON/ReBoN#15]
### Description
- 카테고리 & 태그 별로 모든 Shop 리스트 가져오는 기능
- 가게 이름 검색도 가능

[request]
- 카테고리 id (필수)
- List<태그 id> (비어있을 수도, 여러개를 고를수도 있음)
- 가게 이름 (선택)

[response]
- List<ShopResponse>
  - 가게 id
  - 가게 이름
  - 평점
  - List<TagResponse>
    - 태그 id
    - 태그 이름

### Todo
- [ ] 필터링을 통해 가게 목록 가져오기
  - [x] 카테고리 필터링
  - [ ] 위치 태그 필터링
  - [ ] 가게 이름 필터링 

### ETC
