### ISSUE TITLE
패키지 구조 결정 & 도메인 구조 생성

### ISSUE THREAD

**Issue by KJunseo** [RE-BON/ReBoN#2]
### Description
package by layer or package by feature 패키지 구조 결정 후, 도메인 구조 생성

### Todo
- [ ] 패키지 구조 공부해오기
- [ ] 패키지 구조 결정
- [ ] 도메인 구조 생성

### ETC
