### ISSUE TITLE
브랜치 전략 정하기

### ISSUE THREAD

**Issue by KJunseo** [RE-BON/ReBoN#21]
### Description
git-flow, github-flow 브랜치 전략에 대해 공부해오고, 브랜치 전략 결정하기

### Todo
- [x] git-flow 공부
- [x] github-flow 공부
- [x] 브랜치 전략 정하기

### ETC
