### ISSUE TITLE
컨벤션 정하기

### ISSUE THREAD

**Issue by KJunseo** [RE-BON/ReBoN#22]
### Description
commit 컨벤션, 백엔드, 프론트엔드 코드 컨벤션 공부해오고 정하기

### Todo
- [x] 컨벤션 조사해오기
- [x] commit 컨벤션 정하기
- [x] 백엔드 코드 컨벤션 정하기
- [x] 프론트엔드 코드 컨벤션 정하기

### ETC
