### ISSUE TITLE
Main 페이지 api 연결

### ISSUE THREAD

**Issue by leehyelim0691** [RE-BON/ReBoN#222]
### Description
- 카테고리 별 shop 조회 api 연결
- Sub 카테고리 별 shop 조회 api 연결
- 현재 영업중 토글 shop 조회 api 연결
- 카페, 숙소 에도 해당 태그 이름("한동대" 식당) 추가

### Todo
-  [x] 카테고리 별 shop 조회 api 연결
-  [x]  Sub 카테고리 별 shop 조회 api 연결
-  [x] 현재 영업중 토글 shop 조회 api 연결
-  [x] 카페, 숙소 에도 해당 태그 이름("한동대" 식당) 추가
