### ISSUE TITLE
Detail 페이지 api 연결

### ISSUE THREAD

**Issue by leehyelim0691** [RE-BON/ReBoN#223]
### Description
- 이미지 크기 조정
- map 스타일 수정
- shop 공유 링크 수정

### Todo
- [x] 이미지 크기 조정
- [x] map 스타일 수정
- [x] shop 공유 링크 수정
