### ISSUE TITLE
초기 환경 세팅

### ISSUE THREAD

**Issue by leehyelim0691** [RE-BON/ReBoN#27]
### Description
- React 프로젝트 생성

### Todo
- [x] React 프로젝트 생성
  - [x] 쓸모없는 파일 삭제
- [x] gitignore 설정
- [x] prettier 설정 (vscode 에 적용하는 부분은 따로 블로그 참고) 
- [x] styledComponent 설정 

### ETC
