### ISSUE TITLE
modify 페이지 기능 수정

### ISSUE THREAD

**Issue by Eugenius1st** [RE-BON/ReBoN#277]
### Todo
- [x] modify 페이지 url 연결
- [x] get 요청 받기
- [x] review 페이지 url 연결
- [x] review 페이지 이미지 이름 추가

**Comment by Eugenius1st** [comment]
dd
