### ISSUE TITLE
헤더, 약관, 모달 수정

### ISSUE THREAD

**Issue by Eugenius1st** [RE-BON/ReBoN#290]
### Description
헤더, 약관, 모달 수정
### Todo
- [x] 헤더, 
- [x] 약관, 
- [x] 모달 수정
- [x] 리뷰 작성시 로그인 유도
- [ ] 이미지 업로드 modify onclick 만들고, 스타일 수정
- [ ] 아이디 중복확인 확인
