### ISSUE TITLE
commit 컨벤션, 백 & 프론트 코드 컨벤션, 팀 문화 wiki에 정리

### ISSUE THREAD

**Issue by KJunseo** [RE-BON/ReBoN#40]
### Description
commit 컨벤션, 백 & 프론트 코드 컨벤션, 팀 문화 wiki에 정리

### Todo
- [ ] commit 컨벤션 문서화
- [ ] 백엔드 코드 컨벤션 문서화
- [ ] 프론트엔드 코드 컨벤션 문서화
- [ ] 팀 문화 문서화
