### ISSUE TITLE
새로운 Shop 등록(단일)

### ISSUE THREAD

**Issue by KJunseo** [RE-BON/ReBoN#5]
### Description
- 카테고리 별로 새로운 Shop을 등록하는 기능 개발

### Todo
- [x] 새로운 Shop 등록 API 개발(단일 Shop)
    - [x] 가게의 이름은 존재해야한다.
        - [x] 빈 문자열이나, 공백으로만 이루어진 문자열은 올 수 없다.
    - [x] 카테고리에 맞게 식당, 카페, 숙소 인스턴스가 생성된다. 
  - [x] 레스토랑, 카페인 경우 메뉴 그룹과 메뉴도 등록할 수 있어야한다. 

### ETC
- 인수 테스트는 태그와 카테고리가 완료되어야지 가능할듯?
