### ISSUE TITLE
패키지 구조 변경

### ISSUE THREAD

**Issue by KJunseo** [RE-BON/ReBoN#63]
### Description
패키지 구조를 변경한다
- Tag -> 별개의 패키지로 분리
- Category -> 별개의 패키지로 분리
- Menu -> shop 안으로 이동

### Todo
- [x] Tag 패키지 분리
- [x] Category 패키지 분리
- [x] Menu 패키지 이동
