### ISSUE TITLE
Shop 이미지 저장

### ISSUE THREAD

**Issue by KJunseo** [RE-BON/ReBoN#65]
### Description
이미지를 별도 위치에 저장하고 저장된 url을 DB에 저장한다.

#### 이미지 저장
이미지 저장이 일어나는 경우

1) 가게 등록 → 관리자(스프링 부트에서 thyemleaf 사용)
2) 리뷰 등록 → 일반 유저(프론트 → 백)

1. - 프론트 → 백 (presignedUrl 요청)
    - 프론트 → s3 이미지 저장 (presignedUrl 활용)
    - 프론트 → 백 (이미지 url) → db 이미지 url 저장 
    
    > 이미지 업로드는 presignedUrl을 이용하시면 됩니다. 그러면 Client에서 Server를 거치지 않고 Client에서 즉시 S3로 안전하게 전송해줍니다. 불필요한 중간단계가 사라지는거죠. 그렇다고 Client에서 특별히 더 추가되는 부하는 없고요. (presignedUrl을 서버에 요청하는 작업이 추가되긴 하지만 이건 일반적인 API요청과 동일하기 때문에 이미지 업로드에 비하면 상대적으로 부하가 없다라고 보면 되요.)
    > 
    [https://www.inflearn.com/chats/278798](https://www.inflearn.com/chats/278798)
    
    > 기존의 user -> server -> s3 flow로 이미지 업로드를 진행 할 경우 Presigned url를 사용해 구현할 경우와 대비해서
    '네트워크 대역폭'이 증가하여 속도적인 측면에서 단점을 가진다
    > 
    
    [https://www.inflearn.com/questions/286989](https://www.inflearn.com/questions/286989)
    
2. - 프론트 → 백 (multipartfile)
    - 백 → s3 이미지 저장
    - 백 → db 이미지 url 저장

### Todo
- [x] 이미지 s3에 저장
- [x] 이미지 url DB에 저장
- [x] mocking을 이용한 이미지 저장 테스트
- [x] Thymeleaf를 사용하여 가게 등록 관리자 페이지 만들기
